{{- $serviceName := .serviceName -}}
{{- $serviceValues := index .Values $serviceName -}}
{{- if $serviceValues.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "254carbon-access-layer.fullname" $ }}-{{ $serviceName }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "254carbon-access-layer.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  replicas: {{ $serviceValues.replicaCount }}
  selector:
    matchLabels:
      {{- include "254carbon-access-layer.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  template:
    metadata:
      labels:
        {{- include "254carbon-access-layer.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $serviceName }}
    spec:
      {{- include "254carbon-access-layer.imagePullSecrets" $ | nindent 6 }}
      serviceAccountName: {{ include "254carbon-access-layer.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $serviceName }}
          securityContext:
            {{- toYaml $.Values.security.containerSecurityContext | nindent 12 }}
          image: {{ include "254carbon-access-layer.image" (dict "repository" $serviceValues.image.repository "tag" $serviceValues.image.tag) }}
          imagePullPolicy: {{ $serviceValues.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $serviceValues.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "254carbon-access-layer.fullname" $ }}-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml $serviceValues.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "254carbon-access-layer.fullname" $ }}-{{ $serviceName }}-service
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "254carbon-access-layer.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: {{ $serviceValues.service.type }}
  ports:
    - port: {{ $serviceValues.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "254carbon-access-layer.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
