# OpenAPI specification for the Gateway Service
# NOTE: Kept minimal intentionally; endpoints are documented in code.
info:
  description: API specification for the gateway service
  title: Gateway Service API
  version: 1.0.0
openapi: 3.0.3
paths:
  /health:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  service:
                    type: string
                  status:
                    type: string
                  version:
                    type: string
                type: object
          description: Service is healthy
      summary: Health check
servers:
- description: Development server
  url: http://localhost:8000
