# Prometheus configuration for 254Carbon Access Layer
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gateway service
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Auth service
  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8010']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Streaming service
  - job_name: 'streaming'
    static_configs:
      - targets: ['streaming:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Entitlements service
  - job_name: 'entitlements'
    static_configs:
      - targets: ['entitlements:8011']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Metrics service
  - job_name: 'metrics'
    static_configs:
      - targets: ['metrics:8012']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s