# OpenAPI specification for the Streaming Service
# Intended for quick local tooling and contract checks.
info:
  description: API specification for the streaming service
  title: Streaming Service API
  version: 1.0.0
openapi: 3.0.3
paths:
  /health:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  service:
                    type: string
                  status:
                    type: string
                  version:
                    type: string
                type: object
          description: Service is healthy
      summary: Health check
  /stats:
    get:
      summary: Service statistics
      responses:
        '200':
          description: Streaming service statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  websocket:
                    type: object
                  sse:
                    type: object
                  subscriptions:
                    type: object
                  kafka:
                    type: object
                  supported_topics:
                    type: object
servers:
- description: Development server
  url: http://localhost:8001
